result = 4/0 # 분모에는 0이 올수 없기때문에 오류가 발생한다.

print(result)
